# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# Please consult the lectures

ANS: vectors are one dimensional array and matrices are two dimensional array.

**2. How to import `NumPy` library?**

In [4]:
# To avoid overwriting the output, please code here
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [5]:
list_1 = [1,2,3,4,5]

In [6]:
# To avoid overwriting the output, please code here
my_array=np.array(list_1)
my_array

array([1, 2, 3, 4, 5])

In [7]:
my_array=np.array(list_1)
my_array,type(my_array)


(array([1, 2, 3, 4, 5]), numpy.ndarray)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [8]:
# To avoid overwriting the output, please code here
num=np.arange(6)
num

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [9]:
# To avoid overwriting the output, please code here
num=np.zeros(5)
num

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [10]:
# To avoid overwriting the output, please code here
num=np.linspace(0,0,12)
num
num.reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [11]:
# To avoid overwriting the output, please code here
num=np.ones(5)
print(num)

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [12]:
# To avoid overwriting the output, please code here
num=np.linspace(10,10,5)
num


array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [13]:
# To avoid overwriting the output, please code here
num=np.arange(52,100,2)
num

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [14]:
# To avoid overwriting the output, please code here
num=np.linspace(0,1,10, retstep=True)
num

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [15]:
# To avoid overwriting the output, please code here
num=np.arange(0,25)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
# Generating vector array

In [17]:
# To avoid overwriting the output, please code here
num=np.arange(0,25)
num
num.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
# To avoid overwriting the output, please code here
num=np.arange(0,25)
num

num.shape=(5,5)
num
# yes, shape instead of reshape.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [20]:
# To avoid overwriting the output, please code here
num=np.arange(0.1,2.6,.10)
num
num.reshape(5,5)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [21]:
# To avoid overwriting the output, please code here
n=np.linspace(0,24,25,dtype=int)
n
n.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [ ]:
# Please consult the lectures.
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

yes,arange() takes 3rd argument as step size.
yes, linspace() take 3rd argument as no of point we want.

difference between linspace allows you to specify the number of steps and arange allows you to

specify the size of the steps .


**15. How to generate a single random integer number using NumPy built-in function?**

In [22]:
# To avoid overwriting the output, please code here
np.random.randint(1,20)

2

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [23]:
# To avoid overwriting the output, please code here
num=np.random.rand(35)
num
x=num.reshape(7,5)
print(x)

[[0.30374483 0.72850864 0.06010521 0.9101331  0.92150439]
 [0.8318971  0.23181881 0.03302423 0.3406482  0.07133245]
 [0.69934163 0.44400936 0.76506165 0.35242059 0.5251236 ]
 [0.7710724  0.75029789 0.84566234 0.45234222 0.33545918]
 [0.0952363  0.09187045 0.51667334 0.90241967 0.76023287]
 [0.72450249 0.97249357 0.81838076 0.41320958 0.62122764]
 [0.49952807 0.62155715 0.95268804 0.70414834 0.99759828]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [24]:
# To avoid overwriting the output, please code here
num=np.identity(5)
num=num*5
num

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck